#!/bin/sh
dusage=$(df -m | grep -vE '^tmpfs|cdrom' | sed s/%//g |  awk '{ if($5 > 50) print $0;}')
fscount=$(df -m | grep -vE '^Filesystem|tmpfs|cdrom' | sed s/%//g | awk '{ if($5 > 50) print $0;}' | wc -l)
if [ $fscount -ge 2 ]; then
echo "$dusage" | mail -s "Disk Space Alert On $(hostname) at $(date)" vijay.seerla@dxc.com
  fi
